# Generated by Django 6.1 on 2026-09-07 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('venta', 'Venta'), ('merma', 'Merma')], max_length=20, verbose_name='tipo')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('motivo', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_de_inventario', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['producto', 'creado_en'], name='movimiento_por_producto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='movimiento_inventario_cantidad_distinta_de_cero'), models.CheckConstraint(condition=models.Q(models.Q(('cantidad__gt', 0), ('tipo', 'ingreso')), models.Q(('cantidad__lt', 0), ('tipo', 'venta')), models.Q(('cantidad__lt', 0), ('tipo', 'merma')), _connector='OR'), name='movimiento_inventario_signo_segun_tipo'), models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'merma'), _negated=True), models.Q(('motivo', ''), _negated=True), _connector='OR'), name='movimiento_inventario_merma_con_motivo')],
            },
        ),
    ]
