# Generated by Django 6.1 on 2026-09-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_de_inventario', to='ventas.venta', verbose_name='venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'venta'), _negated=True), ('venta__isnull', False), _connector='OR'), name='movimiento_inventario_de_venta_con_su_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['ingreso', 'merma']), _negated=True), ('venta__isnull', True), _connector='OR'), name='movimiento_inventario_manual_sin_venta'),
        ),
    ]
