# Generated by Django 6.1 on 2026-09-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
            ],
            options={
                'verbose_name': 'merma',
                'verbose_name_plural': 'mermas',
                'ordering': ['-creado_en'],
                'proxy': True,
                'default_permissions': ('add', 'view'),
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.movimientoinventario',),
        ),
    ]
