# Generated by Django 6.1 on 2026-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('inventario', '0003_merma'),
        ('ventas', '0002_instantanea_en_la_linea_de_venta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimientoinventario',
            name='movimiento_inventario_merma_con_motivo',
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'merma'), _negated=True), ('motivo__regex', '\\S'), _connector='OR'), name='movimiento_inventario_merma_con_motivo'),
        ),
    ]
