# Generated by Django 6.1 on 2026-09-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('inventario', '0004_merma_con_motivo_no_en_blanco'),
        ('ventas', '0003_pedido_anticipado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'venta')), fields=('venta', 'producto'), name='movimiento_inventario_una_salida_por_venta_y_producto'),
        ),
    ]
