# Generated by Django 6.1 on 2026-09-01 17:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'alérgeno',
                'verbose_name_plural': 'alérgenos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160, unique=True, verbose_name='nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('porcion', models.CharField(blank=True, default='', help_text='Qué es una unidad vendible: «paquete de 30 g», «vaso de 200 ml».', max_length=60, verbose_name='porción')),
                ('energia_kcal', models.PositiveIntegerField(blank=True, null=True, verbose_name='energía (kcal)')),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='proteínas (g)')),
                ('carbohidratos_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='carbohidratos (g)')),
                ('azucares_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='azúcares (g)')),
                ('grasas_totales_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='grasas totales (g)')),
                ('grasas_saturadas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='grasas saturadas (g)')),
                ('sodio_mg', models.PositiveIntegerField(blank=True, null=True, verbose_name='sodio (mg)')),
                ('activo', models.BooleanField(default=True, verbose_name='en el catálogo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlergeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('alergeno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones', to='catalogo.alergeno')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'alérgeno declarado',
                'verbose_name_plural': 'alérgenos declarados',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalogo.ProductoAlergeno', to='catalogo.alergeno', verbose_name='alérgenos declarados'),
        ),
        migrations.AddConstraint(
            model_name='productoalergeno',
            constraint=models.UniqueConstraint(fields=('producto', 'alergeno'), name='producto_alergeno_unico'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='producto_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('grasas_saturadas_g__isnull', True), ('grasas_totales_g__isnull', True), ('grasas_saturadas_g__lte', models.F('grasas_totales_g')), _connector='OR'), name='producto_saturadas_no_superan_totales'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('azucares_g__isnull', True), ('carbohidratos_g__isnull', True), ('azucares_g__lte', models.F('carbohidratos_g')), _connector='OR'), name='producto_azucares_no_superan_carbohidratos'),
        ),
    ]
