# Generated by Django 6.1 on 2026-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_clave',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='clave de la imagen'),
        ),
    ]
