# Generated by Django 6.1 on 2026-09-12 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('personas', '0005_estudiante_foto_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(choices=[('billetera', 'Billetera'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='medio de pago')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='personas.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_de_venta', to='catalogo.producto', verbose_name='producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'línea de venta',
                'verbose_name_plural': 'líneas de venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['creado_en'], name='venta_por_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estudiante', 'creado_en'], name='venta_por_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estudiante__isnull', False), ('medio_pago', 'billetera')), models.Q(('estudiante__isnull', True), ('medio_pago__in', ['efectivo', 'transferencia'])), _connector='OR'), name='venta_medio_de_pago_segun_el_cliente'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='linea_venta_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.UniqueConstraint(fields=('venta', 'producto'), name='linea_venta_un_renglon_por_producto'),
        ),
    ]
