# Generated by Django 6.1 on 2026-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaventa',
            name='azucares_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='azúcares (g)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='carbohidratos_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='carbohidratos (g)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='energia_kcal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='energía (kcal)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='grasas_saturadas_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='grasas saturadas (g)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='grasas_totales_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='grasas totales (g)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='porcion',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='porción'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio unitario'),
            # `preserve_default=False`: el cero es **solo** para rellenar las filas
            # que ya existieran, no el valor por defecto del modelo. Una línea de
            # venta sin precio congelado no puede volver a ocurrir.
            #
            # Que ese relleno sea cero y no el precio de hoy es deliberado, y es la
            # razón de ser de esta migración: el precio actual del producto **no**
            # es el que tuvo la venta, y usarlo sería escribir en el historial una
            # cifra inventada — justo lo que `HU-22` prohíbe. Cualquier línea
            # anterior a este cambio salió de una prueba manual de las últimas
            # horas: `TT-80` se integró hoy y el entorno desplegado está congelado.
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='proteinas_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='proteínas (g)'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='sodio_mg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='sodio (mg)'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='linea_venta_precio_no_negativo'),
        ),
    ]
