# Generated by Django 6.1 on 2026-09-18 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_estudiante_foto_clave'),
        ('ventas', '0002_instantanea_en_la_linea_de_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAnticipado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de entrega'), ('entregado', 'Entregado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('entregado_en', models.DateTimeField(blank=True, null=True, verbose_name='entregado en')),
            ],
            options={
                'verbose_name': 'pedido anticipado',
                'verbose_name_plural': 'pedidos anticipados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('punto_de_venta', 'Punto de venta'), ('reserva', 'Reserva anticipada')], default='punto_de_venta', max_length=20, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='cajero'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cajero__isnull', False), ('origen', 'punto_de_venta')), models.Q(('cajero__isnull', True), ('estudiante__isnull', False), ('origen', 'reserva')), _connector='OR'), name='venta_cajero_segun_su_origen'),
        ),
        migrations.AddField(
            model_name='pedidoanticipado',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entregados', to=settings.AUTH_USER_MODEL, verbose_name='entregado por'),
        ),
        migrations.AddField(
            model_name='pedidoanticipado',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_anticipado', to='ventas.venta', verbose_name='venta'),
        ),
        migrations.AddIndex(
            model_name='pedidoanticipado',
            index=models.Index(fields=['estado', 'creado_en'], name='pedido_por_estado'),
        ),
        migrations.AddConstraint(
            model_name='pedidoanticipado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entregado_en__isnull', True), ('entregado_por__isnull', True), ('estado', 'pendiente')), models.Q(('entregado_en__isnull', False), ('entregado_por__isnull', False), ('estado', 'entregado')), _connector='OR'), name='pedido_entrega_completa_o_ninguna'),
        ),
    ]
