# Generated by Django 6.1 on 2026-09-19 21:01

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pedido_anticipado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDeCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='jornada')),
                ('base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base para cambio')),
                ('efectivo_contado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='efectivo contado')),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='efectivo esperado')),
                ('motivo', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo de la diferencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_de_caja', to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
            ],
            options={
                'verbose_name': 'cierre de caja',
                'verbose_name_plural': 'cierres de caja',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('fecha',), name='cierre_de_caja_uno_por_jornada'), models.CheckConstraint(condition=models.Q(('base__gte', 0), ('efectivo_contado__gte', 0), ('efectivo_esperado__gte', 0)), name='cierre_de_caja_montos_no_negativos'), models.CheckConstraint(condition=models.Q(('efectivo_contado', django.db.models.expressions.CombinedExpression(models.F('base'), '+', models.F('efectivo_esperado'))), ('motivo__regex', '\\S'), _connector='OR'), name='cierre_de_caja_diferencia_con_motivo')],
            },
        ),
    ]
