# Generated by Django 6.1 on 2026-08-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('password', ''), _negated=True), name='usuario_contrasena_no_vacia'),
        ),
    ]
