# Generated by Django 6.1 on 2026-09-16 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_estudiante_foto_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='limite_diario', to='personas.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'límite diario',
                'verbose_name_plural': 'límites diarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='limite_diario_monto_positivo')],
            },
        ),
    ]
