# Generated by Django 6.1 on 2026-09-16 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('personas', '0005_estudiante_foto_clave'),
        ('restricciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_bloqueados', to='personas.estudiante', verbose_name='estudiante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto bloqueado',
                'verbose_name_plural': 'productos bloqueados',
                'ordering': ['producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'producto'), name='un_solo_bloqueo_por_estudiante_y_producto')],
            },
        ),
    ]
