# Generated by Django 6.1 on 2026-09-16 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('personas', '0005_estudiante_foto_clave'),
        ('restricciones', '0002_restriccionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionAlergeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('alergeno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueos', to='catalogo.alergeno', verbose_name='alérgeno')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alergenos_bloqueados', to='personas.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'alérgeno bloqueado',
                'verbose_name_plural': 'alérgenos bloqueados',
                'ordering': ['alergeno__nombre'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'alergeno'), name='un_solo_bloqueo_por_estudiante_y_alergeno')],
            },
        ),
    ]
