# Generated by Django 6.1 on 2026-09-16 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('personas', '0005_estudiante_foto_clave'),
        ('restricciones', '0003_restriccionalergeno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoDeRestriccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('bloqueo', 'Bloqueo'), ('retiro', 'Retiro')], max_length=10, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre en ese momento')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_de_restriccion', to=settings.AUTH_USER_MODEL, verbose_name='quién')),
                ('alergeno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_de_restriccion', to='catalogo.alergeno', verbose_name='alérgeno')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_de_restriccion', to='personas.estudiante', verbose_name='estudiante')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_de_restriccion', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'asiento de restricción',
                'verbose_name_plural': 'asientos de restricción',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estudiante', 'creado_en'], name='asiento_por_estudiante')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alergeno__isnull', True), ('producto__isnull', False)), models.Q(('alergeno__isnull', False), ('producto__isnull', True)), _connector='OR'), name='asiento_sobre_un_producto_o_un_alergeno')],
            },
        ),
    ]
