# Generated by Django 6.1 on 2026-09-16 16:31

from django.conf import settings
from django.db import migrations, models


def _marcar_lo_que_ya_existia(apps, schema_editor):
    """Pone `sobre` en los asientos anteriores, deduciéndolo de sus claves ajenas.

    Los asientos que escribió `TT-104` son todos de producto o de alérgeno —el
    límite diario no se asentaba— y se distinguen por cuál de las dos claves
    tienen puesta. **Es la última vez que esa deducción vale**: a partir de aquí
    lo dice el campo, que es de lo que trata este cambio.

    El `default='producto'` de arriba deja bien a los de producto por casualidad;
    esto corrige los de alérgeno, que son los que estarían mal.
    """
    Asiento = apps.get_model("restricciones", "AsientoDeRestriccion")
    Asiento.objects.filter(alergeno__isnull=False).update(sobre="alergeno")
    Asiento.objects.filter(producto__isnull=False).update(sobre="producto")


def _sin_vuelta_atras(apps, schema_editor):
    """Revertir no tiene nada que deshacer: la columna entera se va con la
    migración inversa, y lo que había antes se deduce igual de las claves."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_clave'),
        ('personas', '0005_estudiante_foto_clave'),
        ('restricciones', '0004_asientoderestriccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asientoderestriccion',
            name='asiento_sobre_un_producto_o_un_alergeno',
        ),
        migrations.AddField(
            model_name='asientoderestriccion',
            name='sobre',
            field=models.CharField(choices=[('producto', 'Producto'), ('alergeno', 'Alérgeno'), ('limite_diario', 'Límite diario')], default='producto', max_length=20, verbose_name='sobre'),
            # El `default` existe **solo para poder añadir la columna** a una tabla
            # con filas: sin él, `makemigrations` abre un prompt que nadie contesta.
            # `preserve_default=False` lo retira del modelo en cuanto la columna
            # está, para que ningún asiento futuro herede un «producto» que nadie
            # eligió.
            preserve_default=False,
        ),
        migrations.RunPython(_marcar_lo_que_ya_existia, _sin_vuelta_atras),
        migrations.AddConstraint(
            model_name='asientoderestriccion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alergeno__isnull', True), ('producto__isnull', False), ('sobre', 'producto')), models.Q(('alergeno__isnull', False), ('producto__isnull', True), ('sobre', 'alergeno')), models.Q(('alergeno__isnull', True), ('producto__isnull', True), ('sobre', 'limite_diario')), _connector='OR'), name='asiento_coherente_con_lo_que_restringe'),
        ),
    ]
