# Generated by Django 6.1 on 2026-09-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_estudiante_foto_clave'),
        ('restricciones', '0005_remove_asientoderestriccion_asiento_sobre_un_producto_o_un_alergeno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionesDelEstudiante',
            fields=[
            ],
            options={
                'verbose_name': 'restricciones de un estudiante',
                'verbose_name_plural': 'restricciones por estudiante',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('personas.estudiante',),
        ),
    ]
