# Generated by Django 6.1 on 2026-09-06 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_estudiante_foto_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billetera', to='personas.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'billetera',
                'verbose_name_plural': 'billeteras',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga'), ('venta', 'Venta'), ('devolucion', 'Devolución')], max_length=20, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='billetera.billetera', verbose_name='billetera')),
            ],
            options={
                'verbose_name': 'movimiento de billetera',
                'verbose_name_plural': 'movimientos de billetera',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['billetera', 'creado_en'], name='movimiento_por_billetera')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto', 0), _negated=True), name='movimiento_monto_distinto_de_cero'), models.CheckConstraint(condition=models.Q(models.Q(('monto__lt', 0), ('tipo', 'venta')), models.Q(('monto__gt', 0), ('tipo', 'recarga')), models.Q(('monto__gt', 0), ('tipo', 'devolucion')), _connector='OR'), name='movimiento_signo_segun_tipo')],
            },
        ),
    ]
