# Generated by Django 6.1 on 2026-09-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobilletera',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_de_billetera', to='ventas.venta', verbose_name='venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientobilletera',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'venta'), _negated=True), ('venta__isnull', False), _connector='OR'), name='movimiento_de_venta_con_su_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientobilletera',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'recarga'), _negated=True), ('venta__isnull', True), _connector='OR'), name='movimiento_de_recarga_sin_venta'),
        ),
    ]
