# Generated by Django 6.1 on 2026-08-30 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('unica', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='institucion', to=settings.AUTH_USER_MODEL, verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'institución educativa',
                'verbose_name_plural': 'instituciones educativas',
                'constraints': [models.UniqueConstraint(fields=('unica',), name='institucion_unica'), models.CheckConstraint(condition=models.Q(('unica', 1)), name='institucion_unica_es_uno')],
            },
        ),
    ]
