# Generated by Django 6.1 on 2026-08-30 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='documento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acudiente', to=settings.AUTH_USER_MODEL, verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'acudiente',
                'verbose_name_plural': 'acudientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='documento')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='personas.acudiente', verbose_name='acudiente')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['nombre'],
            },
        ),
    ]
