"""`TT-41`. El estado del estudiante y su fecha de baja (`HU-51`, `DT-12`).

Las dos columnas nacen con valor para las filas existentes sin necesidad de un
paso de relleno: `estado` toma su valor por defecto —todo el que ya estaba
matriculado sigue activo— y `dado_de_baja_en` es nulo, que es lo coherente.

**No hay ninguna operación de borrado aquí, y no puede haberla.** La baja es
lógica: un `DELETE` destruiría el historial del que se reconstruye el saldo
(`INV-2`, `DT-4`).
"""

# Generated by Django 6.1 on 2026-09-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_estudiante_codigo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dado_de_baja_en',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='dado de baja en'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('desactivado', 'Desactivado'), ('baja', 'De baja')], default='activo', editable=False, max_length=12, verbose_name='estado'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'desactivado', 'baja'])), name='estudiante_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dado_de_baja_en__isnull', False), ('estado', 'baja')), models.Q(models.Q(('estado', 'baja'), _negated=True), ('dado_de_baja_en__isnull', True)), _connector='OR'), name='estudiante_fecha_de_baja_coherente'),
        ),
    ]
