# Generated by Django 6.1 on 2026-09-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_estudiante_estado_de_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_clave',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='clave de la fotografía'),
        ),
    ]
